# /etc/kubernetes/enc/enc.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - secretbox:
          keys:
            - name: key
              secret: MOvM/bdzZaJcipNJpynNqrrwLctOJ1c/lWxT6MsU3a0= # Replace with head -c 32 /dev/urandom | base64
      - identity: {}
