apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: apps
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICJhdXRoIjogIlpHbGtaWEpwYTJzNlNHOUthWEpTZG5WS2NuUjFVMEU0UlE9PSIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson