apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess
  namespace: apps
  labels:
    app: chess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
        - name: chess
          image: diderikk/chess:v1.0.7
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: chess-secrets
          livenessProbe:
            httpGet:
              path: /api/hello/live
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 3600
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/hello/ready
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2