apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  namespace: database
  labels:
    app: database-backup
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # Preferably should be remote
  local:
    path: /mnt/postgres_backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker3
