apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: database
  labels:
    app: database-backup
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [database-backup]}
