apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  namespace: apps
  labels:
    app: simple-chat
    rel: stable
    need: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
        rel: stable
        need: database
    spec:
      serviceAccountName: simple-chat-sa
      automountServiceAccountToken: false
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
        - name: simple-chat
          image: diderikk/simple-chat:v1.3.3@sha256:caf1cb2c135492b4efcba2c99c153c3db06fc2529b4bfca6169e1d824203a9c4
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            runAsNonRoot: true
            runAsGroup: 11112
            runAsUser: 65534
            capabilities:
              drop: ['all']
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "20m"
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: simple-chat-secrets
          livenessProbe:
            httpGet:
              path: /api/hello/live
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 1800
            failureThreshold: 2