apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  selector:
    matchExpressions:
      - {key: name, operator: In, values: [database-pv]}