apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: apps
  labels:
    app: portfolio
    rel: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
        rel: stable
    spec:
      serviceAccountName: portfolio-sa
      automountServiceAccountToken: false
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
        - name: portfolio
          image: diderikk/portfolio:v1.3.0@sha256:b32d9bbd59bcc42b71f2df512afb43132e26250dd095978a9bed5bf686ded2b7
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            runAsNonRoot: true
            runAsGroup: 11112
            runAsUser: 11111
            capabilities:
              drop: ['all']
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: portfolio-secrets
