apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: apps
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: diderikk/portfolio:v1.2.3@sha256:1c0e95fb9716be84646a3101d0f8e367210772eff82423330ac5c9601e4010cd
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: portfolio-secrets
