apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: database
  labels:
    app: pgbouncer
spec:
  type: ClusterIP
  ports:
    - port: 6432
      targetPort: 5432
  selector:
    app: pgbouncer
