apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-frontend
  namespace: apps
  labels:
    app: chess-frontend
    rel: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-frontend
  template:
    metadata:
      labels:
        app: chess-frontend
        rel: stable
      annotations:
        container.apparmor.security.beta.kubernetes.io/chess-frontend: localhost/deny-write
    spec:
      serviceAccountName: chess-frontend-sa
      containers:
        - name: chess-frontend
          image: diderikk/chess-frontend:v1.2.4@sha256:5738e274c75461235341342c303c27ea934420b8d691d180acfc3d23e1c07990
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080