apiVersion: v1
kind: Service
metadata:
  name: chess-frontend-service
  namespace: apps
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8080
  selector:
    app: chess-frontend