apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: database
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 5432
      targetPort: 6432
  selector:
    app: pgbouncer
