apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  namespace: apps
  annotations:
  # Required for websockets in Nginx Ingress
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        }
spec:
  tls:
    - hosts:
      - elixirapi.me
      secretName: tls-secrets
  ingressClassName: nginx
  rules:
  - host: elixirapi.me
    http:
      paths:
      # - path: /api/hello
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: simple-chat-service
      #       port:
      #         number: 4000
      - path: /chess-socket
        pathType: Prefix
        backend:
          service:
            name: chess-service
            port:
              number: 4000
      - path: /simple-chat-socket
        pathType: Prefix
        backend:
          service:
            name: chess-service
            port:
              number: 4000