apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  namespace: apps
  labels:
    app: simple-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
    spec:
      initContainers:
        - name: simple-chat-builder
          image: diderikk/simple-chat-builder:v1.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: simple-chat-secrets
          command: ["sh", '-c', 'mix ecto.setup']
      containers:
        - name: simple-chat
          image: diderikk/simple-chat:v1.2.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: simple-chat-secrets
          livenessProbe:
            httpGet:
              path: /api/simplechat/hello/live
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 1800
            failureThreshold: 2