apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  namespace: apps
  labels:
    app: simple-chat
    rel: stable
  annotations:
    container.apparmor.security.beta.kubernetes.io/simple-chat: localhost/deny-write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
        rel: stable
    spec:
      serviceAccountName: simple-chat-sa
      containers:
        - name: simple-chat
          image: diderikk/simple-chat:v1.3.1@sha256:4fc5d8fcdbdcb14e04871fd1e7fc83d67c1ba53f626674b2fd90153d92a05a8d
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: simple-chat-secrets
          livenessProbe:
            httpGet:
              path: /api/hello/live
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 1800
            failureThreshold: 2