apiVersion: v1
kind: Service
metadata:
  name: simple-chat-service
  namespace: apps
  labels:
    app: simple-chat
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 4000
  selector:
    app: simple-chat