apiVersion: apps/v1
kind: Deployment
metadata:
  name: issueboard
  namespace: apps
  labels:
    app: issueboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issueboard
  template:
    metadata:
      labels:
        app: issueboard
    spec:
      initContainers:
        - name: issueboard-init
          image: diderikk/issueboard:v1.1.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: issueboard-secrets
          command: ["sh", '-c', 'rails db:migrate']
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
      containers:
        - name: issueboard
          image: diderikk/issueboard:v1.1.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: issueboard-secrets