apiVersion: v1
kind: Service
metadata:
  name: issueboard-service
  namespace: apps
  labels:
    app: issueboard
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: backend-svc
    - port: 3000
      name: frontend-svc
  selector:
    app: issueboard