apiVersion: v1
kind: Service
metadata:
  name: issueboard-service
  namespace: apps
  labels:
    app: issueboard
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: issueboard

---

apiVersion: v1
kind: Service
metadata:
  name: issueboard-frontend-service
  namespace: apps
  labels:
    app: issueboard-frontend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: issueboard-frontend