apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: apps
  labels:
    app: portfolio
    rel: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
        rel: stable
    spec:
      serviceAccountName: portfolio-sa
      automountServiceAccountToken: false
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
        - name: portfolio
          image: diderikk/portfolio:v1.3.1@sha256:bc7aa8f5f7c67c8ed0ec33ca723e836fea278eb923ed55895b230ecedb418dea
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            runAsNonRoot: true
            runAsGroup: 11112
            runAsUser: 11111
            capabilities:
              drop: ['all']
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: portfolio-secrets
