apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafana
  labels:
    app: grafana
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/default
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker2

# helm repo add grafana https://grafana.github.io/helm-charts &&
#   helm repo update &&
#   helm upgrade --install grafana-k8s-monitoring grafana/k8s-monitoring \
#     --namespace "grafana" --create-namespace --values - <<EOF
# cluster:
#   name: "my-cluster"

# externalServices:
#   loki:
#     host: "https://logs-prod-008.grafana.net"
#     basicAuth:
#       username: "396171"
#       password: "secrets.json"

# metrics:
#   enabled: false

# kube-state-metrics: {enabled: false}
# prometheus-node-exporter: {enabled: false}
# prometheus-operator-crds: {enabled: false}
# opencost: {enabled: false}
# EOF