apiVersion: apps/v1
kind: Deployment
metadata:
  name: livebook
  namespace: apps
  labels:
    app: livebook
    rel: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livebook
  template:
    metadata:
      labels:
        app: livebook
        rel: stable
    spec:
      containers:
        - name: livebook
          image: ghcr.io/livebook-dev/livebook:0.11.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: livebook-secrets
          volumeMounts:
            - mountPath: /home/livebook
              name: livebook-home
      volumes:
        - name: livebook-home
          persistentVolumeClaim:
            claimName: livebook-pvc