apiVersion: v1
kind: PersistentVolume
metadata:
  name: livebook-pv
  namespace: apps
  labels:
    app: livebook
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker3
