apiVersion: v1
kind: Service
metadata:
  name: livebook-service
  namespace: apps
  labels:
    app: livebook
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8080
  selector:
    app: livebook
